<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007204800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vocabulary_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kanji VARCHAR(255) DEFAULT NULL, reading VARCHAR(255) DEFAULT NULL, translation VARCHAR(255) DEFAULT NULL, sheet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_44FA2C328B1206A5 ON vocabulary_item (sheet_id)');
        $this->addSql('CREATE TABLE vocabulary_sheet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B5BF1C08F675F31B ON vocabulary_sheet (author_id)');
        $this->addSql('ALTER TABLE vocabulary_item ADD CONSTRAINT FK_44FA2C328B1206A5 FOREIGN KEY (sheet_id) REFERENCES vocabulary_sheet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary_sheet ADD CONSTRAINT FK_B5BF1C08F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vocabulary_item DROP CONSTRAINT FK_44FA2C328B1206A5');
        $this->addSql('ALTER TABLE vocabulary_sheet DROP CONSTRAINT FK_B5BF1C08F675F31B');
        $this->addSql('DROP TABLE vocabulary_item');
        $this->addSql('DROP TABLE vocabulary_sheet');
    }
}
