<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708003406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answer_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_correct BOOLEAN NOT NULL, given_kanji VARCHAR(255) DEFAULT NULL, given_reading VARCHAR(255) DEFAULT NULL, given_translation VARCHAR(255) DEFAULT NULL, asked_kanji VARCHAR(255) NOT NULL, asked_reading VARCHAR(255) NOT NULL, asked_translation VARCHAR(255) NOT NULL, quiz_attempt_id INT NOT NULL, question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50ACCD17F8FE9957 ON answer_attempt (quiz_attempt_id)');
        $this->addSql('CREATE INDEX IDX_50ACCD171E27F6BF ON answer_attempt (question_id)');
        $this->addSql('CREATE TABLE quiz_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, max_score INT NOT NULL, mode VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, quiz_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB6AFC6F675F31B ON quiz_attempt (author_id)');
        $this->addSql('CREATE INDEX IDX_AB6AFC6853CD175 ON quiz_attempt (quiz_id)');
        $this->addSql('ALTER TABLE answer_attempt ADD CONSTRAINT FK_50ACCD17F8FE9957 FOREIGN KEY (quiz_attempt_id) REFERENCES quiz_attempt (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer_attempt ADD CONSTRAINT FK_50ACCD171E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quiz_attempt ADD CONSTRAINT FK_AB6AFC6F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quiz_attempt ADD CONSTRAINT FK_AB6AFC6853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE answer_attempt DROP CONSTRAINT FK_50ACCD17F8FE9957');
        $this->addSql('ALTER TABLE answer_attempt DROP CONSTRAINT FK_50ACCD171E27F6BF');
        $this->addSql('ALTER TABLE quiz_attempt DROP CONSTRAINT FK_AB6AFC6F675F31B');
        $this->addSql('ALTER TABLE quiz_attempt DROP CONSTRAINT FK_AB6AFC6853CD175');
        $this->addSql('DROP TABLE answer_attempt');
        $this->addSql('DROP TABLE quiz_attempt');
    }
}
