<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260725175708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_public BOOLEAN NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECA209CDF675F31B ON folder (author_id)');
        $this->addSql('CREATE TABLE folder_quiz (folder_id INT NOT NULL, quiz_id INT NOT NULL, PRIMARY KEY (folder_id, quiz_id))');
        $this->addSql('CREATE INDEX IDX_BD8DDC87162CB942 ON folder_quiz (folder_id)');
        $this->addSql('CREATE INDEX IDX_BD8DDC87853CD175 ON folder_quiz (quiz_id)');
        $this->addSql('CREATE TABLE folder_user (folder_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (folder_id, user_id))');
        $this->addSql('CREATE INDEX IDX_940CF05C162CB942 ON folder_user (folder_id)');
        $this->addSql('CREATE INDEX IDX_940CF05CA76ED395 ON folder_user (user_id)');
        $this->addSql('ALTER TABLE folder ADD CONSTRAINT FK_ECA209CDF675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folder_quiz ADD CONSTRAINT FK_BD8DDC87162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE folder_quiz ADD CONSTRAINT FK_BD8DDC87853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE folder_user ADD CONSTRAINT FK_940CF05C162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE folder_user ADD CONSTRAINT FK_940CF05CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CDF675F31B');
        $this->addSql('ALTER TABLE folder_quiz DROP CONSTRAINT FK_BD8DDC87162CB942');
        $this->addSql('ALTER TABLE folder_quiz DROP CONSTRAINT FK_BD8DDC87853CD175');
        $this->addSql('ALTER TABLE folder_user DROP CONSTRAINT FK_940CF05C162CB942');
        $this->addSql('ALTER TABLE folder_user DROP CONSTRAINT FK_940CF05CA76ED395');
        $this->addSql('DROP TABLE folder');
        $this->addSql('DROP TABLE folder_quiz');
        $this->addSql('DROP TABLE folder_user');
    }
}
